# utils/config.py

# LLM
MODEL_NAME = "gemma4:e2b"

# STT
WHISPER_MODEL_SIZE = "small"
WHISPER_LANGUAGE = "de"
WHISPER_BEAM_SIZE = 5
WHISPER_VAD_MIN_SILENCE_MS = 300

# Recorder
SAMPLE_RATE = 16000
CHUNK_DURATION = 0.03

# Main / Buffer-Management
SILENCE_THRESHOLD_TIME = 2.0
MIN_AUDIO_TIME = 0.5
ENERGY_THRESHOLD = 0.01
